version: '3'

services:
  app:
    build:
      context: .
      dockerfile: multi-stage.dockerfile
    deploy:
      replicas: 4
    expose:
      - 4000
    environment:
      - PING_LISTEN_PORT=4000

  reverse-proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    image: nginx
    ports:
      - "80:8080"
